### PR TITLE
Structured network reservoirs

### PR DESCRIPTION
**Pull request by jdmattern**
Reservoirs split in reach network and calls to initialize and run basic level pool reservoirs

## Additions

-

## Removals

-

## Changes

-

## Testing

1.

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [ ] Windows
- [ ] Linux
- [ ] Browser

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by jameshalgren** [comment]
@jdmattern-noaa 
Reviewing this today.

**Comment by jdmattern** [comment]
@jameshalgren This now has inheritance for MC_Reach and MC_Reservoir and passes the upstream flows to the reservoir.

**Comment by jdmattern** [comment]
@jameshalgren I think I am a little confused about the conclusion of your conversation about sorted segs with Ryan. Is this current method of unsorted, therefore maintaining the order of execution what we want or do we want to sort and add another variable for the order of execution?

https://github.com/jameshalgren/t-route/blob/structured-network-compute_plus-reservoirs/src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py#L604

**Comment by jameshalgren** [comment]
> @jameshalgren I think I am a little confused about the conclusion of your conversation about sorted segs with Ryan. Is this current method of unsorted, therefore maintaining the order of execution what we want or do we want to sort and add another variable for the order of execution?
> 
> https://github.com/jameshalgren/t-route/blob/structured-network-compute_plus-reservoirs/src/python_routing_v02/compute_nhd_routing_SingleSeg_v02.py#L604

Short answer -- in your reservoir PR, do whatever you need to for reservoirs. I think we can sort out the combined use case on final review.

**Comment by jameshalgren** [comment]
Following instructions, performed unit tests from README.py. 

Then executed the following commandline execution tests: 
- [x] python compute_nhd_routing_SingleSeg_v02.py --test pocono1 -t -v --debuglevel 1
- [x] python compute_nhd_routing_SingleSeg_v02.py -f ../../test/input/yaml/CustomInput.yaml
- [x] python compute_nhd_routing_SingleSeg_v02.py -t -n Mainstems_CONUS -v --debuglevel 1 --parallel by-network --nts 288 --cpu-pool 6
- [ ] python compute_nhd_routing_SingleSeg_v02.py -t -n Mainstems_CONUS -v --debuglevel 1 --parallel by-subnetwork-jit-clustered --subnet-size 100 --nts 288 --cpu-pool 6

The last test still does not work with the subnetworks -- we will need to fix that in the main PR.

**Pull request merged**
